language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install ;
- v8_install ;
- dcmtk_install ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: vvgHcbQ/WNs9f4terhXmNmTz6dk28qlRfXEdaMrrt+Mp5qiY0PMpjr1QYMKIJAujNt1rSd5dQNseyMr+CTfO/bSHBmma50MMxIygoKcISS60vfdCApWs80g5lKnJityVcVYh+6vVMU8g65LZD3Py6IkzOFmjUMmau75VL8g4iQI/G4YRX9jq1j0YAEjjUCsda6tt4UDxTVS0lFCYoETyah7W1nL70NI3c5PYx3FlfV9lNwcPomTVnP5ywPlJI2kL1yCFT8LJ95VtP0U8PbFTr7dzOLVfyN9ogQXKY54IA2l8xaWNn1ZkpzW2f6bLCchdA7KZTO6juJMpOpHybUhHeIn1mW04rcEf0CK2yvyhSMlzsI4NISVVjp5S353ZfCynNAPRt8jxm9Fpzq7RaLJM/f7QFy0cV8DKO3YQkTFL8pPEk5wod3FGrZ8F5XLepjZqolV5tpJzT0XD09yRxJc+S4Whv+YV3BNf9g+GcNCtLa2Pa/dYiqwngi+VbPvd4PjqqqkI9i7u5YeyQIZpvO0E89iTennVY8eugwJ4QnQZ5Ag9V3f55CnLsT9vKHJf3O4kkenjVArBKwSJsrXKl9/qV2NYrqj6xeek4g9JZf+4aKPwbVhD+/8dkgKya1Lh6p8sJnZl0e//Bvgy+AkUii+z0roTMmY6eJ7MLYB7CTi47Yw=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait
  100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
